version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tigoune/hbo/tigoune-hbocontentbatch/
hooks:
  BeforeInstall:
    - location: stop_service
      timeout: 300
      runas: root
  Install:
    - location: install_service
      timeout: 300
      runas: root
  AfterInstall:
    - location: install_service
      timeout: 300
      runas: root
