//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.11 at 08:11:43 AM COT 
//


package com.tigoune.hbo.model.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}offer-type"/>
 *         &lt;element ref="{}offer-subtype"/>
 *         &lt;element ref="{}unique-id"/>
 *         &lt;element ref="{}start-date"/>
 *         &lt;element ref="{}end-date"/>
 *         &lt;element ref="{}free-preview"/>
 *         &lt;element ref="{}first-burst"/>
 *         &lt;element ref="{}last-burst"/>
 *         &lt;element ref="{}publish-countries"/>
 *         &lt;element ref="{}affiliates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offerType",
    "offerSubtype",
    "uniqueId",
    "startDate",
    "endDate",
    "freePreview",
    "firstBurst",
    "lastBurst",
    "publishCountries",
    "affiliates"
})
@XmlRootElement(name = "offering")
public class Offering {

    @XmlElement(name = "offer-type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String offerType;
    @XmlElement(name = "offer-subtype", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String offerSubtype;
    @XmlElement(name = "unique-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String uniqueId;
    @XmlElement(name = "start-date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "end-date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "free-preview", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String freePreview;
    @XmlElement(name = "first-burst", required = true)
    protected FirstBurst firstBurst;
    @XmlElement(name = "last-burst", required = true)
    protected LastBurst lastBurst;
    @XmlElement(name = "publish-countries", required = true)
    protected PublishCountries publishCountries;
    @XmlElement(required = true)
    protected Affiliates affiliates;

    /**
     * Gets the value of the offerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferType() {
        return offerType;
    }

    /**
     * Sets the value of the offerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferType(String value) {
        this.offerType = value;
    }

    /**
     * Gets the value of the offerSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferSubtype() {
        return offerSubtype;
    }

    /**
     * Sets the value of the offerSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferSubtype(String value) {
        this.offerSubtype = value;
    }

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueId(String value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the freePreview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreePreview() {
        return freePreview;
    }

    /**
     * Sets the value of the freePreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreePreview(String value) {
        this.freePreview = value;
    }

    /**
     * Gets the value of the firstBurst property.
     * 
     * @return
     *     possible object is
     *     {@link FirstBurst }
     *     
     */
    public FirstBurst getFirstBurst() {
        return firstBurst;
    }

    /**
     * Sets the value of the firstBurst property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirstBurst }
     *     
     */
    public void setFirstBurst(FirstBurst value) {
        this.firstBurst = value;
    }

    /**
     * Gets the value of the lastBurst property.
     * 
     * @return
     *     possible object is
     *     {@link LastBurst }
     *     
     */
    public LastBurst getLastBurst() {
        return lastBurst;
    }

    /**
     * Sets the value of the lastBurst property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastBurst }
     *     
     */
    public void setLastBurst(LastBurst value) {
        this.lastBurst = value;
    }

    /**
     * Gets the value of the publishCountries property.
     * 
     * @return
     *     possible object is
     *     {@link PublishCountries }
     *     
     */
    public PublishCountries getPublishCountries() {
        return publishCountries;
    }

    /**
     * Sets the value of the publishCountries property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishCountries }
     *     
     */
    public void setPublishCountries(PublishCountries value) {
        this.publishCountries = value;
    }

    /**
     * Gets the value of the affiliates property.
     * 
     * @return
     *     possible object is
     *     {@link Affiliates }
     *     
     */
    public Affiliates getAffiliates() {
        return affiliates;
    }

    /**
     * Sets the value of the affiliates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Affiliates }
     *     
     */
    public void setAffiliates(Affiliates value) {
        this.affiliates = value;
    }

}
