//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.11 at 08:11:43 AM COT 
//


package com.tigoune.hbo.model.metadata;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}runtime"/>
 *         &lt;element ref="{}Credits"/>
 *         &lt;element ref="{}AudioTracks"/>
 *         &lt;element ref="{}formats"/>
 *         &lt;element ref="{}images"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runtime",
    "credits",
    "subtitles",
    "audioTracks",
    "formats",
    "images"
})
@XmlRootElement(name = "video")
public class Video {

    @XmlElement(required = true)
    protected BigInteger runtime;
    @XmlElement(name = "Credits", required = true)
    protected Credits credits;
    @XmlElement(name = "Subtitles", required = true)
    protected Subtitles subtitles;
    @XmlElement(name = "AudioTracks", required = true)
    protected AudioTracks audioTracks;
    @XmlElement(required = true)
    protected Formats formats;
    @XmlElement(required = true)
    protected Images images;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the runtime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRuntime() {
        return runtime;
    }

    /**
     * Sets the value of the runtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRuntime(BigInteger value) {
        this.runtime = value;
    }

    /**
     * Gets the value of the credits property.
     * 
     * @return
     *     possible object is
     *     {@link Credits }
     *     
     */
    public Credits getCredits() {
        return credits;
    }

    /**
     * Sets the value of the credits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credits }
     *     
     */
    public void setCredits(Credits value) {
        this.credits = value;
    }

    /**
     * Gets the value of the audioTracks property.
     * 
     * @return
     *     possible object is
     *     {@link AudioTracks }
     *     
     */
    /**
     * Gets the value of the subtitles property.
     * 
     * @return
     *     possible object is
     *     {@link Subtitles }
     *     
     */
    public Subtitles getSubtitles() {
        return subtitles;
    }

    /**
     * Sets the value of the subtitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subtitles }
     *     
     */
    public void setSubtitles(Subtitles value) {
        this.subtitles = value;
    }
    
    public AudioTracks getAudioTracks() {
        return audioTracks;
    }

    /**
     * Sets the value of the audioTracks property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioTracks }
     *     
     */
    public void setAudioTracks(AudioTracks value) {
        this.audioTracks = value;
    }

    /**
     * Gets the value of the formats property.
     * 
     * @return
     *     possible object is
     *     {@link Formats }
     *     
     */
    public Formats getFormats() {
        return formats;
    }

    /**
     * Sets the value of the formats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formats }
     *     
     */
    public void setFormats(Formats value) {
        this.formats = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link Images }
     *     
     */
    public Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link Images }
     *     
     */
    public void setImages(Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
